### ISSUE TITLE
Add test cases based on IEEE 13-bus system

### ISSUE THREAD

**Issue by AnjoMan** [opusonesolutions/carsons#13]
IEEE 13 contains a number of different cable configurations and calculated impedances. It would be a good idea to add these as test cases for `carsons`

The test cases can be found at http://sites.ieee.org/pes-testfeeders/files/2017/08/feeder13.zip

**Comment by EmilyYLMa** [comment]
I think we already use some of the IEEE 13 cables. For example, the _ABC_line_geometry_phase_impedance_ is based off of the 601 configuration on IEEE13. The _CBN_line_geometry_phase_impedance is based off of the 603 config, and the _CN_line_geometry_phase_impedance_ is based off of the 605 config.

**Comment by EmilyYLMa** [comment]
Might be good to document the tests indicating that we are using IEEE13 configuration.

**Comment by AnjoMan** [comment]
Good point. i added some annotations here https://github.com/opusonesolutions/carsons/pull/10/commits/1ca4c66a4355693f4818df28c1c0590f1cc32c86

**Comment by EmilyYLMa** [comment]
@AnjoMan Can I close this issue?

**Comment by AnjoMan** [comment]
Closing this as the work has already been done. See https://github.com/opusonesolutions/carsons/blob/master/tests/test_carsons.py where the test cases have been labelled with the corresponding line configuration in IEEE 4/13 test data.
