### ISSUE TITLE
Check validity of equation when computing P

### ISSUE THREAD

**Issue by kdheepak** [opusonesolutions/carsons#17]
I wanted to confirm that this equation is correct?

https://github.com/opusonesolutions/carsons/blob/d58461d884e1e7140fbf6ba1846e859268c63f7f/carsons/carsons.py#L137

Shouldn't it be this instead?

```python
−π * k**4 * cos(4 * θ) / 1536
```

Or is there some simplification I'm missing?

**Comment by AnjoMan** [comment]
I think you are right! looking at the [vismor source](https://vismor.com/documents/power_systems/transmission_lines/S2.SS1.php) and the [van dommelen source](https://core.ac.uk/download/pdf/34634673.pdf) it seems like maybe the coefficient is swapped with the 4th term of Q.

Would you be interested in submitting a PR to fix this?
