### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by spark706** [opusonesolutions/carsons#27]
I am attempting to load this package into:
Windows 10
Python 3.6
Anaconda 5.1

I receive the following error
```
(base) C:\Users\XXXXXXXXX>pip install carsons
Collecting carsons
  Downloading https://files.pythonhosted.org/packages/72/83/b0e2954f67741643b1fd2be62d3f1f6a5b96f99ad1c16fa4a0faabcff2eb/carsons-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\XXXXXXXXX\AppData\Local\Temp\pip-build-el644y7h\carsons\setup.py", line 31, in <module>
        long_description=readme(),
      File "C:\Users\XXXXXXXXX\AppData\Local\Temp\pip-build-el644y7h\carsons\setup.py", line 10, in readme
        return f.read()
      File "C:\Users\XXXXXXXXX\AppData\Local\Continuum\anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1163: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\XXXXXXXXX\AppData\Local\Temp\pip-build-el644y7h\carsons\
```

What do I need to do to solve this?

**Comment by etimberg** [comment]
@spark706 what appears to be happening is that your Python version is assuming the default encoding is [Code Page 1252](https://en.wikipedia.org/wiki/Windows-1252). However, these files in this project should all be UTF-8 encoded and read as such.

One way to check your encoding would be to run the following. On my system, I get `'UTF-8'`.

```python
import locale
os_encoding = locale.getpreferredencoding()
print(os_encoding)
```

In terms of fixes, I think we can make an update to force using UTF-8 encoding when reading the file in setup.py. I've opened #28 to make this update. In the meantime, you could try changing your default encoding to UTF-8 and see if that fixes the issue.

**Comment by AnjoMan** [comment]
Thanks for reporting this, @spark706! I've tagged a new release https://github.com/opusonesolutions/carsons/releases/tag/0.2.2 so you should be able to install with no special commands.

**Comment by spark706** [comment]
Thanks!
